package Main;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;

public class Glossary {
//    public static void main(String[] args) {
//        define();
//    }

    public static void define() {
        System.out.println("■ Glossary ■" );

        HashMap<String, String> definitions = new HashMap<>();
        definitions.put(" - Account Receivables Days (Collection period)", "Number of days it takes for a company to collect its accounts receivable.");
        definitions.put(" - Accounts Payables Days (Settlement period)", "Number of days it takes for a company to pay its accounts payable.");
        definitions.put(" - Days inventory on hand", "Number of days inventory is held before it is sold.");
        definitions.put(" - Inventory Turnover Ratio", "A ratio showing how many times a company's inventory is sold and replaced over a period.");
        definitions.put(" - Fixed Asset (Non-Current) Turnover", "A financial ratio that measures a company's efficiency in using its fixed assets to generate sales.");
        definitions.put(" - Total Asset Turnover (TAT)", "A financial ratio that measures a company's efficiency in using its assets to generate sales.");
        definitions.put(" - Cash Coverage Ratio", "A ratio that measures the ability of a company to cover its interest obligations with its cash flow.");
        definitions.put(" - Cash Flow To Debt Ratio", "A ratio that measures a company's ability to repay its debt with its cash flow.");
        definitions.put(" - Debt Ratio", "A ratio that measures the proportion of a company's assets that are financed by debt.");
        definitions.put(" - Debt To Equity Ratio - ALL LIABILITIES", "A ratio that measures the proportion of a company's total liabilities to its shareholders' equity.");
        definitions.put(" - Debt To Equity Ratio - INTEREST BEARING LIABILITIES", "A ratio that measures the proportion of a company's interest-bearing liabilities to its shareholders' equity.");
        definitions.put(" - Equity Multiplier (EM)", "A financial ratio that measures a company's financial leverage.");
        definitions.put(" - Times Interest Earned Ratio", "A ratio that measures a company's ability to meet its debt obligations based on its earnings.");
        definitions.put(" - Dividend Cover", "A ratio that measures the number of times a company can pay dividends to its shareholders.");
        definitions.put(" - Dividend Yield (DY)", "A ratio that measures the amount of cash dividends paid out to shareholders relative to the market value per share.");
        definitions.put(" - Earnings Yield (EY) (Inverse of PE)", "A ratio that measures the earnings generated by each dollar of investment.");
        definitions.put(" - Headline Earnings Per Share (EPS)", "A measure of the portion of a company's profit allocated to each outstanding share of common stock.");
        definitions.put(" - Market Price to Book (using Market Capitalisation)", "A ratio used to compare a company's market value to its book value.");
        definitions.put(" - Market Price to Book (Using Share price)", "A ratio used to compare a company's share price to its book value per share.");
        definitions.put(" - Market Value Added (MVA)", "A measure of the difference between the market value of a company and the capital contributed by investors.");
        definitions.put(" - Market Value Added (MVA) PER SHARE", "A measure of the difference between the market value of a company and the capital contributed by investors, on a per-share basis.");
        definitions.put(" - Pay-out Ratio", "A ratio that measures the proportion of earnings paid out as dividends to shareholders.");
        definitions.put(" - Price Earnings Ratio (P/E)", "A ratio that measures the price of a company's stock relative to its earnings per share.");
        definitions.put(" - Retention Ratio (Ploughback/plowback ratio)", "A ratio that measures the proportion of earnings retained in the business rather than paid out as dividends.");
        definitions.put(" - Return to Shareholder (Holding Period Return (HPR))", "The total return earned by a shareholder over a holding period.");
        definitions.put(" - Acid Test Ratio (Quick ratio)", "A ratio that measures a company's ability to meet its short-term obligations with its most liquid assets.");
        definitions.put(" - Current Ratio", "A ratio that measures a company's ability to pay its short-term liabilities with its short-term assets.");
        definitions.put(" - Gross Margin on Sales", "A ratio that measures a company's profitability by comparing its gross profit to its sales.");
        definitions.put(" - Net Margin (NM)", "A ratio that measures a company's profitability by comparing its net profit to its sales.");
        definitions.put(" - Operating Profit Margin", "A ratio that measures a company's profitability by comparing its operating profit to its sales.");
        definitions.put(" - Net Profit on Sales after Tax", "A ratio that measures a company's profitability by comparing its net profit after tax to its sales.");
        definitions.put(" - Return on Equity (ROE)", "A ratio that measures a company's profitability by comparing its net profit to its shareholders' equity.");
        definitions.put(" - Return on Total Assets (ROA)", "A ratio that measures a company's profitability by comparing its net profit to its total assets.");
        definitions.put(" - Return on Total Assets (ROA) (EBIT)", "ROA (EBIT) evaluates the use of ALL assets to generate income BEFORE Interest and Tax.");
        definitions.put(" - Solvency Test", "A test to determine a company's ability to meet its long-term obligations.");
        definitions.put(" - Sustainable Growth Rate (SGR) (also known as g)", "The rate at which a company can grow its sales, earnings, and dividends at a consistent rate without having to increase its debt or equity financing.");
        definitions.put(" - Du Pont Analysis", "A framework for analyzing a company's return on equity by breaking it down into three components: profit margin, asset turnover, and financial leverage.");
        definitions.put(" - Net Asset Value Per Share", "The value of a company's total assets minus its total liabilities, divided by the number of outstanding shares.");
        definitions.put(" - Present Value (PV)", "The current value of a future sum of money or stream of cash flows, given a specified rate of return.");
        definitions.put(" - Future Value (FV)", "The value of an asset or cash at a specified date in the future that is equivalent in value to a specified sum today.");
        definitions.put(" - Net Present Value (NPV)", "The difference between the present value of cash inflows and the present value of cash outflows over a period of time.");
        definitions.put(" - Internal Rate of Return (IRR)", "A metric used in financial analysis to estimate the profitability of potential investments.");
        definitions.put(" - Yield to Maturity (YTM)", "The total return anticipated on a bond if the bond is held until it matures.");
        definitions.put(" - Macaulay Bond Duration", "Duration measures the sensitivity of the price of a bond or other debt instrument to changes in interest rates. It is the weighted average time until a bond's cash flows are received, discounted to present value.");
        definitions.put(" - Bond Convexity", "A measure of the curvature in the relationship between bond prices and bond yields.");
        definitions.put(" - Present Value Interest Factor of Annuity (PVIFA)", "The Present Value Interest Factor of Annuity (PVIFA) calculates the present value of a series of equal cash flows, discounted at a given rate. It helps in determining the present value of an annuity.");
        definitions.put(" - Future Value Interest Factor of Annuity (FVIFA)", "The Future Value Interest Factor of Annuity (FVIFA) calculates the future value of a series of equal cash flows, compounded at a given rate. It helps in determining the future value of an annuity.");
        definitions.put(" - Current Yield", "Current Yield is a financial ratio that measures the annual return on a bond as a percentage of its current market price.");
        definitions.put(" - Bond Price", "Bond Price refers to the present value of the bond's future cash flows, including both coupon payments and the face value, discounted at the market interest rate.");

        System.out.println(definitions.size());
        List<String> sortedKeys = new ArrayList<>(definitions.keySet());

        Collections.sort(sortedKeys);
        for(String keys : sortedKeys){
            System.out.println(keys + "  :  " + definitions.get(keys));
            System.out.println();
        }
    }
}
